name: Developer Tests

on: push

jobs:
  # Then name of the job is launch-test
  launch-tests:
    runs-on: ubuntu-latest
    # All the steps are executed in the container openjda:8-jdk-alpine
    container: openjdk:8-jdk-alpine

    steps:
      # We checkout the repository's code
      - uses: actions/checkout@v1
      # We lunch the tests
      - name: Change permissions
        run:  chmod +x ./mvnw
      - name: Launch Test with Maven
        run: ./mvnw test